# Generated by Django 5.2 on 2025-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_productmodel_delete_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['product__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('product', 'name')},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена модели продукта', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sku',
        ),
    ]
