# Generated by Django 5.2 on 2025-04-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['product__name', 'name'], 'verbose_name': 'Модель продукта', 'verbose_name_plural': 'Модели продуктов'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_models/', verbose_name='Изображение модели'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Описание модели'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена модели продукта', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.product', verbose_name='Продукт'),
        ),
    ]
