# Generated by Django 5.2 on 2025-04-21 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('document_number', models.PositiveIntegerField(help_text='Автоматически генерируемый номер документа', unique=True, verbose_name='Номер документа')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10, verbose_name='Тип документа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал документа',
                'verbose_name_plural': 'Журнал документов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
