# Generated by Django 5.2 on 2025-05-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа'),
        ),
    ]
